name: Anchor CI
on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Install Solana Development Environment
        run: |
          curl --proto '=https' --tlsv1.2 -sSfL https://solana-install.solana.workers.dev | bash
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Verify Installation
        run: |
          source $HOME/.cargo/env
          rustc --version
          solana --version
          anchor --version
          node --version
          npm --version
      
      - name: Install Node Dependencies
        run: |
          yarn install

      - name: Generate Keypair for Testing
        run: |
          source $HOME/.cargo/env
          solana-keygen new --no-bip39-passphrase
      
      - name: Anchor Build
        run: |
          source $HOME/.cargo/env
          anchor build
      
      - name: Anchor Test
        run: |
          source $HOME/.cargo/env
          anchor test